//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMS.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולות.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפוך פעיל.
        /// </summary>
        internal static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפיכת משתמש לפעיל.
        /// </summary>
        internal static string ActivateUserTitle {
            get {
                return ResourceManager.GetString("ActivateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניהול.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי תחרות.
        /// </summary>
        internal static string CompetitionDetails {
            get {
                return ResourceManager.GetString("CompetitionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום.
        /// </summary>
        internal static string CompetitionEndTime {
            get {
                return ResourceManager.GetString("CompetitionEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עודכן לאחרונה.
        /// </summary>
        internal static string CompetitionLastModified {
            get {
                return ResourceManager.GetString("CompetitionLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עודכן לאחרונה.
        /// </summary>
        internal static string CompetitionLastModifiedHeader {
            get {
                return ResourceManager.GetString("CompetitionLastModifiedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שופט ראשי.
        /// </summary>
        internal static string CompetitionMainReferee {
            get {
                return ResourceManager.GetString("CompetitionMainReferee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון שופט ראשי.
        /// </summary>
        internal static string CompetitionMainRefereePhone {
            get {
                return ResourceManager.GetString("CompetitionMainRefereePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת משחקים.
        /// </summary>
        internal static string CompetitionMatchesListTab {
            get {
                return ResourceManager.GetString("CompetitionMatchesListTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגרלות.
        /// </summary>
        internal static string CompetitionMatchesTab {
            get {
                return ResourceManager.GetString("CompetitionMatchesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג התחרות.
        /// </summary>
        internal static string CompetitionMethod {
            get {
                return ResourceManager.GetString("CompetitionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טורניר נוק-אאוט.
        /// </summary>
        internal static string CompetitionMethod_Knockout {
            get {
                return ResourceManager.GetString("CompetitionMethod.Knockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string CompetitionName {
            get {
                return ResourceManager.GetString("CompetitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string CompetitionNameHeader {
            get {
                return ResourceManager.GetString("CompetitionNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת שחקנים.
        /// </summary>
        internal static string CompetitionPlayers {
            get {
                return ResourceManager.GetString("CompetitionPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקנים.
        /// </summary>
        internal static string CompetitionPlayersTab {
            get {
                return ResourceManager.GetString("CompetitionPlayersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אסמכתא.
        /// </summary>
        internal static string CompetitionReferenceId {
            get {
                return ResourceManager.GetString("CompetitionReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרויות.
        /// </summary>
        internal static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית התנחומים.
        /// </summary>
        internal static string CompetitionSection_Consolation {
            get {
                return ResourceManager.GetString("CompetitionSection.Consolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית הגמר.
        /// </summary>
        internal static string CompetitionSection_Final {
            get {
                return ResourceManager.GetString("CompetitionSection.Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית הגמר זוגות.
        /// </summary>
        internal static string CompetitionSection_PairsFinal {
            get {
                return ResourceManager.GetString("CompetitionSection.PairsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוקדמות זוגות.
        /// </summary>
        internal static string CompetitionSection_PairsQualifying {
            get {
                return ResourceManager.GetString("CompetitionSection.PairsQualifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוקדמות.
        /// </summary>
        internal static string CompetitionSection_Qualifying {
            get {
                return ResourceManager.GetString("CompetitionSection.Qualifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ תחרויות.
        /// </summary>
        internal static string CompetitionsFileLabel {
            get {
                return ResourceManager.GetString("CompetitionsFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מועדון.
        /// </summary>
        internal static string CompetitionSite {
            get {
                return ResourceManager.GetString("CompetitionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון מועדון.
        /// </summary>
        internal static string CompetitionSitePhone {
            get {
                return ResourceManager.GetString("CompetitionSitePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת תחרויות.
        /// </summary>
        internal static string CompetitionsList {
            get {
                return ResourceManager.GetString("CompetitionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        internal static string CompetitionStartTime {
            get {
                return ResourceManager.GetString("CompetitionStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string CompetitionStartTimeHeader {
            get {
                return ResourceManager.GetString("CompetitionStartTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        internal static string CompetitionStatus {
            get {
                return ResourceManager.GetString("CompetitionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחרות הסתיימה.
        /// </summary>
        internal static string CompetitionStatus_Finished {
            get {
                return ResourceManager.GetString("CompetitionStatus.Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשחקים נוצרו.
        /// </summary>
        internal static string CompetitionStatus_MatchesCreated {
            get {
                return ResourceManager.GetString("CompetitionStatus.MatchesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוצבו השחקנים.
        /// </summary>
        internal static string CompetitionStatus_Positioned {
            get {
                return ResourceManager.GetString("CompetitionStatus.Positioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחרות החלה.
        /// </summary>
        internal static string CompetitionStatus_Started {
            get {
                return ResourceManager.GetString("CompetitionStatus.Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרות.
        /// </summary>
        internal static string CompetitionTitle {
            get {
                return ResourceManager.GetString("CompetitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג התחרות.
        /// </summary>
        internal static string CompetitionType {
            get {
                return ResourceManager.GetString("CompetitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג.
        /// </summary>
        internal static string CompetitionTypeHeader {
            get {
                return ResourceManager.GetString("CompetitionTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string CompetitionTypeNameHeader {
            get {
                return ResourceManager.GetString("CompetitionTypeNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוגי תחרויות.
        /// </summary>
        internal static string CompetitionTypes {
            get {
                return ResourceManager.GetString("CompetitionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון תוצאות.
        /// </summary>
        internal static string CompetitionUpdateResultsTab {
            get {
                return ResourceManager.GetString("CompetitionUpdateResultsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת תחרות חדשה.
        /// </summary>
        internal static string CreateCompetition {
            get {
                return ResourceManager.GetString("CreateCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת תחרות.
        /// </summary>
        internal static string CreateCompetitionLink {
            get {
                return ResourceManager.GetString("CreateCompetitionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור סוג תחרות.
        /// </summary>
        internal static string CreateCompetitionType {
            get {
                return ResourceManager.GetString("CreateCompetitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת סוג תחרות.
        /// </summary>
        internal static string CreateCompetitionTypeHeader {
            get {
                return ResourceManager.GetString("CreateCompetitionTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפוך ללא פעיל.
        /// </summary>
        internal static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפיכת משתמש ללא פעיל.
        /// </summary>
        internal static string DeactivateUserTitle {
            get {
                return ResourceManager.GetString("DeactivateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם למחוק את.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור מחיקה.
        /// </summary>
        internal static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכה.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת פרטי סוג תחרות.
        /// </summary>
        internal static string EditCompetitionTypeHeader {
            get {
                return ResourceManager.GetString("EditCompetitionTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טורניר.
        /// </summary>
        internal static string EliminationTournament {
            get {
                return ResourceManager.GetString("EliminationTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקבה.
        /// </summary>
        internal static string FemaleAbbr {
            get {
                return ResourceManager.GetString("FemaleAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string FilterByDate {
            get {
                return ResourceManager.GetString("FilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיבוב.
        /// </summary>
        internal static string FilterByRound {
            get {
                return ResourceManager.GetString("FilterByRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גמר.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיים תחרות.
        /// </summary>
        internal static string FinishCompetition {
            get {
                return ResourceManager.GetString("FinishCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית תנחומים?.
        /// </summary>
        internal static string HasConsolation {
            get {
                return ResourceManager.GetString("HasConsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עזרה.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עזרה ותמיכה.
        /// </summary>
        internal static string HelpAndSupport {
            get {
                return ResourceManager.GetString("HelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראשי.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינה.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת קובץ תחרויות.
        /// </summary>
        internal static string ImportCompetitions {
            get {
                return ResourceManager.GetString("ImportCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת קובץ שחקנים.
        /// </summary>
        internal static string LoadCompetitionPlayersHeader {
            get {
                return ResourceManager.GetString("LoadCompetitionPlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה למערכת.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זכר.
        /// </summary>
        internal static string MaleAbbr {
            get {
                return ResourceManager.GetString("MaleAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמשים.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק&apos; בשובר שיוויון.
        /// </summary>
        internal static string MatchBreakPoint {
            get {
                return ResourceManager.GetString("MatchBreakPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string MatchDateHeader {
            get {
                return ResourceManager.GetString("MatchDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקנים.
        /// </summary>
        internal static string MatchPlayersHeader {
            get {
                return ResourceManager.GetString("MatchPlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פסילה.
        /// </summary>
        internal static string MatchResult_Disqualification {
            get {
                return ResourceManager.GetString("MatchResult.Disqualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפסקה.
        /// </summary>
        internal static string MatchResult_Pause {
            get {
                return ResourceManager.GetString("MatchResult.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרישה.
        /// </summary>
        internal static string MatchResult_Retirement {
            get {
                return ResourceManager.GetString("MatchResult.Retirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצחון.
        /// </summary>
        internal static string MatchResult_Win {
            get {
                return ResourceManager.GetString("MatchResult.Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        internal static string MatchResultHeader {
            get {
                return ResourceManager.GetString("MatchResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד.
        /// </summary>
        internal static string MatchResultsHeader {
            get {
                return ResourceManager.GetString("MatchResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משח הופסק.
        /// </summary>
        internal static string MatchStatus_Cancelled {
            get {
                return ResourceManager.GetString("MatchStatus.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק הסתיים.
        /// </summary>
        internal static string MatchStatus_Completed {
            get {
                return ResourceManager.GetString("MatchStatus.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק נוצר.
        /// </summary>
        internal static string MatchStatus_Created {
            get {
                return ResourceManager.GetString("MatchStatus.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתעכב.
        /// </summary>
        internal static string MatchStatus_Delayed {
            get {
                return ResourceManager.GetString("MatchStatus.Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהפסקה.
        /// </summary>
        internal static string MatchStatus_Paused {
            get {
                return ResourceManager.GetString("MatchStatus.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוז נקבע.
        /// </summary>
        internal static string MatchStatus_Planned {
            get {
                return ResourceManager.GetString("MatchStatus.Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ממתין ללוז.
        /// </summary>
        internal static string MatchStatus_PlayersAssigned {
            get {
                return ResourceManager.GetString("MatchStatus.PlayersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק החל.
        /// </summary>
        internal static string MatchStatus_Started {
            get {
                return ResourceManager.GetString("MatchStatus.Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערות.
        /// </summary>
        internal static string MatchStatusHeader {
            get {
                return ResourceManager.GetString("MatchStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעה.
        /// </summary>
        internal static string MatchTimeHeader {
            get {
                return ResourceManager.GetString("MatchTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מצב עדכון.
        /// </summary>
        internal static string MatchUpdateStatusHeader {
            get {
                return ResourceManager.GetString("MatchUpdateStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MatchWinner_None {
            get {
                return ResourceManager.GetString("MatchWinner.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן/קב&apos; 1.
        /// </summary>
        internal static string MatchWinner_Player1 {
            get {
                return ResourceManager.GetString("MatchWinner.Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן/קב&apos; 2.
        /// </summary>
        internal static string MatchWinner_Player2 {
            get {
                return ResourceManager.GetString("MatchWinner.Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנצח.
        /// </summary>
        internal static string MatchWinnerHeader {
            get {
                return ResourceManager.GetString("MatchWinnerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיטה.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לציין שם.
        /// </summary>
        internal static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת סוג תחרות.
        /// </summary>
        internal static string NewCompetitionType {
            get {
                return ResourceManager.GetString("NewCompetitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר הזוגות.
        /// </summary>
        internal static string PairsCount {
            get {
                return ResourceManager.GetString("PairsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמה.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לידה.
        /// </summary>
        internal static string PlayerBirthDateHeader {
            get {
                return ResourceManager.GetString("PlayerBirthDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדינה.
        /// </summary>
        internal static string PlayerCountryHeader {
            get {
                return ResourceManager.GetString("PlayerCountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם באנגלית.
        /// </summary>
        internal static string PlayerEnglishNameHeader {
            get {
                return ResourceManager.GetString("PlayerEnglishNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג אירופי.
        /// </summary>
        internal static string PlayerEuropeInternationalRankHeader {
            get {
                return ResourceManager.GetString("PlayerEuropeInternationalRankHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מין.
        /// </summary>
        internal static string PlayerGenderHeader {
            get {
                return ResourceManager.GetString("PlayerGenderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string PlayerLocalNameHeader {
            get {
                return ResourceManager.GetString("PlayerLocalNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג ארצי.
        /// </summary>
        internal static string PlayerNationalRankHeader {
            get {
                return ResourceManager.GetString("PlayerNationalRankHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר שחקנים.
        /// </summary>
        internal static string PlayersCount {
            get {
                return ResourceManager.GetString("PlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא לציין מספר שחקנים..
        /// </summary>
        internal static string PlayersCountIsRequired {
            get {
                return ResourceManager.GetString("PlayersCountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ שחקנים.
        /// </summary>
        internal static string PlayersFileLabel {
            get {
                return ResourceManager.GetString("PlayersFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דירוג נוער.
        /// </summary>
        internal static string PlayerYouthInternationalRankHeader {
            get {
                return ResourceManager.GetString("PlayerYouthInternationalRankHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תצוגת הדפסה.
        /// </summary>
        internal static string PrintMatchesDraw {
            get {
                return ResourceManager.GetString("PrintMatchesDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוקדמות זוגות.
        /// </summary>
        internal static string QualifyingPairsCount {
            get {
                return ResourceManager.GetString("QualifyingPairsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר שחקנים במוקדמות.
        /// </summary>
        internal static string QualifyingPlayersCount {
            get {
                return ResourceManager.GetString("QualifyingPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רבע גמר.
        /// </summary>
        internal static string QuarterFinal {
            get {
                return ResourceManager.GetString("QuarterFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג דירוג.
        /// </summary>
        internal static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בינלאומי אירופאי.
        /// </summary>
        internal static string Ranking_EuropeInternational {
            get {
                return ResourceManager.GetString("Ranking.EuropeInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארצי.
        /// </summary>
        internal static string Ranking_National {
            get {
                return ResourceManager.GetString("Ranking.National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בינלאומי נוער.
        /// </summary>
        internal static string Ranking_YouthInternational {
            get {
                return ResourceManager.GetString("Ranking.YouthInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפס סיסמה.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמת המשתמש &quot;{0}&quot; אופסה, הסיסמה החדשה היא: {1}.
        /// </summary>
        internal static string ResetPasswordCompleted {
            get {
                return ResourceManager.GetString("ResetPasswordCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איפוס סיסמת משתמש.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיבוב.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple. SAMS.
        /// </summary>
        internal static string SAMS {
            get {
                return ResourceManager.GetString("SAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חצי גמר.
        /// </summary>
        internal static string SemiFinal {
            get {
                return ResourceManager.GetString("SemiFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל תחרות.
        /// </summary>
        internal static string StartCompetition {
            get {
                return ResourceManager.GetString("StartCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל טעינה.
        /// </summary>
        internal static string StartImportCompetition {
            get {
                return ResourceManager.GetString("StartImportCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR.
        /// </summary>
        internal static string StartTimeType_AfterRest {
            get {
                return ResourceManager.GetString("StartTimeType.AfterRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB.
        /// </summary>
        internal static string StartTimeType_FollowedBy {
            get {
                return ResourceManager.GetString("StartTimeType.FollowedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB.
        /// </summary>
        internal static string StartTimeType_NotBefore {
            get {
                return ResourceManager.GetString("StartTimeType.NotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string StartTimeType_NotDetermined {
            get {
                return ResourceManager.GetString("StartTimeType.NotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        internal static string StartTimeType_StartTime {
            get {
                return ResourceManager.GetString("StartTimeType.StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום שלישי.
        /// </summary>
        internal static string ThirdPlace {
            get {
                return ResourceManager.GetString("ThirdPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן שחקנים.
        /// </summary>
        internal static string UpdateCompetitionPlayers {
            get {
                return ResourceManager.GetString("UpdateCompetitionPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון שחקנים לתחרות.
        /// </summary>
        internal static string UpdateCompetitionPlayersHeader {
            get {
                return ResourceManager.GetString("UpdateCompetitionPlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נשמר לאחרונה.
        /// </summary>
        internal static string UpdateResults_LastSaveTime {
            get {
                return ResourceManager.GetString("UpdateResults.LastSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור עכשיו.
        /// </summary>
        internal static string UpdateResults_SendUpdatesNow {
            get {
                return ResourceManager.GetString("UpdateResults.SendUpdatesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש &quot;{0}&quot; הפך לפעיל, משתמש זה יוכל מעתה להכנס למערכת..
        /// </summary>
        internal static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש &quot;{0}&quot; הפך ללא פעיל, משתמש זה לא יוכל מעתה להכנס למערכת..
        /// </summary>
        internal static string UserDeactivated {
            get {
                return ResourceManager.GetString("UserDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש.
        /// </summary>
        internal static string UsernameHeader {
            get {
                return ResourceManager.GetString("UsernameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כרטיסים חופשיים זוגות.
        /// </summary>
        internal static string WildcardPairsCount {
            get {
                return ResourceManager.GetString("WildcardPairsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כרטיסים חופשיים.
        /// </summary>
        internal static string WildcardPlayersCount {
            get {
                return ResourceManager.GetString("WildcardPlayersCount", resourceCulture);
            }
        }
    }
}
