//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAMS.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string CompetitionNameHeader {
            get {
                return ResourceManager.GetString("CompetitionNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרויות.
        /// </summary>
        internal static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ תחרויות.
        /// </summary>
        internal static string CompetitionsFileLabel {
            get {
                return ResourceManager.GetString("CompetitionsFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת תחרויות.
        /// </summary>
        internal static string CompetitionsList {
            get {
                return ResourceManager.GetString("CompetitionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string CompetitionStartTimeHeader {
            get {
                return ResourceManager.GetString("CompetitionStartTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תחרות.
        /// </summary>
        internal static string CompetitionTitle {
            get {
                return ResourceManager.GetString("CompetitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג.
        /// </summary>
        internal static string CompetitionTypeHeader {
            get {
                return ResourceManager.GetString("CompetitionTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string CompetitionTypeNameHeader {
            get {
                return ResourceManager.GetString("CompetitionTypeNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוגי תחרויות.
        /// </summary>
        internal static string CompetitionTypes {
            get {
                return ResourceManager.GetString("CompetitionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת תחרות חדשה.
        /// </summary>
        internal static string CreateCompetition {
            get {
                return ResourceManager.GetString("CreateCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת תחרות.
        /// </summary>
        internal static string CreateCompetitionLink {
            get {
                return ResourceManager.GetString("CreateCompetitionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכה.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עזרה.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עזרה ותמיכה.
        /// </summary>
        internal static string HelpAndSupport {
            get {
                return ResourceManager.GetString("HelpAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראשי.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינה.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת קובץ תחרויות.
        /// </summary>
        internal static string ImportCompetitions {
            get {
                return ResourceManager.GetString("ImportCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת קובץ שחקנים.
        /// </summary>
        internal static string LoadCompetitionPlayersHeader {
            get {
                return ResourceManager.GetString("LoadCompetitionPlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת סוג תחרות.
        /// </summary>
        internal static string NewCompetitionType {
            get {
                return ResourceManager.GetString("NewCompetitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ שחקנים.
        /// </summary>
        internal static string PlayersFileLabel {
            get {
                return ResourceManager.GetString("PlayersFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple. SAMS.
        /// </summary>
        internal static string SAMS {
            get {
                return ResourceManager.GetString("SAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל טעינה.
        /// </summary>
        internal static string StartImportCompetition {
            get {
                return ResourceManager.GetString("StartImportCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן שחקנים.
        /// </summary>
        internal static string UpdateCompetitionPlayers {
            get {
                return ResourceManager.GetString("UpdateCompetitionPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכון שחקנים לתחרות.
        /// </summary>
        internal static string UpdateCompetitionPlayersHeader {
            get {
                return ResourceManager.GetString("UpdateCompetitionPlayersHeader", resourceCulture);
            }
        }
    }
}
