<?xml version="1.0" encoding="utf-8"?><Database Name="SimpleITASAMS" Class="CompetitionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQL2012;Initial Catalog=SimpleITASAMS;Integrated Security=True" SettingsObjectName="Simple.SAMS.Competitions.Data.Properties.Settings" SettingsPropertyName="SimpleITASAMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CompetitionPlayer" Member="CompetitionPlayers">
    <Type Name="CompetitionPlayer">
      <Column Name="CompetitionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Competition_CompetitionPlayer" Member="Competition" ThisKey="CompetitionId" OtherKey="Id" Type="Competition" IsForeignKey="true" />
      <Association Name="Player_CompetitionPlayer" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Competition" Member="Competitions">
    <Type Name="Competition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RowStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceId" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MainReferee" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MainRefereePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SitePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Competition_CompetitionPlayer" Member="CompetitionPlayers" ThisKey="Id" OtherKey="CompetitionId" Type="CompetitionPlayer" />
      <Association Name="Competition_Match" Member="Matches" ThisKey="Id" OtherKey="CompetitionId" Type="Match" />
      <Association Name="CompetitionType_Competition" Member="CompetitionType" ThisKey="TypeId" OtherKey="Id" Type="CompetitionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocalFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NationalRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RowStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LocalLastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnglishFirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnglishLastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsFemale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EuropeInternationalRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YouthInternationalRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IPIN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Player_CompetitionPlayer" Member="CompetitionPlayers" ThisKey="Id" OtherKey="PlayerId" Type="CompetitionPlayer" />
      <Association Name="Player_Match" Member="Matches" ThisKey="Id" OtherKey="Player1" Type="Match" />
      <Association Name="Player_Match1" Member="Matches1" ThisKey="Id" OtherKey="Player2" Type="Match" />
      <Association Name="Player_Match2" Member="Matches2" ThisKey="Id" OtherKey="Player3" Type="Match" />
      <Association Name="Player_Match3" Member="Matches3" ThisKey="Id" OtherKey="Player4" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Section_Match" Member="Matches" ThisKey="Id" OtherKey="SectionId" Type="Match" />
    </Type>
  </Table>
  <Table Name="dbo.CompetitionType" Member="CompetitionTypes">
    <Type Name="CompetitionType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RowStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PlayersCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WildcardPlayersCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QualifyingPlayersCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QualifyingPairsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WildcardPairsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PairsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HasConsolation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ranking" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CompetitionType_Competition" Member="Competitions" ThisKey="Id" OtherKey="TypeId" Type="Competition" />
    </Type>
  </Table>
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RowStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompetitionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Round" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartTimeType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Player2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Player3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Player4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Player1Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player2Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Match_MatchScore" Member="MatchScores" ThisKey="Id" OtherKey="MatchId" Type="MatchScore" />
      <Association Name="Competition_Match" Member="Competition" ThisKey="CompetitionId" OtherKey="Id" Type="Competition" IsForeignKey="true" />
      <Association Name="Player_Match" Member="Player" ThisKey="Player1" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Match1" Member="Player5" ThisKey="Player2" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Match2" Member="Player6" ThisKey="Player3" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Match3" Member="Player7" ThisKey="Player4" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="Section_Match" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatchScore" Member="MatchScores">
    <Type Name="MatchScore">
      <Column Name="MatchId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SetNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Player1Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Player2Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Match_MatchScore" Member="Match" ThisKey="MatchId" OtherKey="Id" Type="Match" IsForeignKey="true" />
    </Type>
  </Table>
</Database>